"""
Alert dispatch: email (SMTP) and webhook (Slack/Discord/Teams/generic).

All credentials are read from environment variables or config.
Both channels silently no-op when not configured — safe to call always.

No new dependencies: uses smtplib, email, and urllib.request (all stdlib).
"""
from __future__ import annotations

import json
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import date
from urllib import request as urllib_request
from urllib.error import URLError

from . import config as cfg


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _is_email_configured() -> bool:
    return bool(cfg.ALERT_EMAIL_TO and cfg.ALERT_EMAIL_FROM and cfg.ALERT_EMAIL_PASSWORD)


def _is_webhook_configured() -> bool:
    return bool(cfg.ALERT_WEBHOOK_URL)


def _build_email_body(packets: dict, regime: dict, alerted: list[str]) -> str:
    """Build plain-text email body summarising today's top setups."""
    lines = [
        f"Swing Engine Alert — {date.today().isoformat()}",
        "=" * 50,
        f"Regime: {regime.get('regime', '?').upper()} | "
        f"Risk: {regime.get('risk_appetite', '?')} | "
        f"VIX: {regime.get('vix_context', '?')}",
    ]

    flags = regime.get("caution_flags", [])
    if flags:
        lines.append(f"CAUTION: {' | '.join(flags)}")

    lines += ["", "TOP ACTIONABLE SETUPS:", "-" * 30]

    for sym in alerted:
        pkt = packets.get(sym, {})
        sc = pkt.get("score", {})
        ez = pkt.get("entry_zone", {})
        setup = pkt.get("setup", {})

        score = sc.get("score", 0)
        bias = sc.get("action_bias", "?")
        setup_type = setup.get("type", "?")
        entry_low = ez.get("entry_low", "?")
        entry_high = ez.get("entry_high", "?")
        stop = ez.get("stop", "?")
        t1 = ez.get("target_1", "?")
        rr = ez.get("rr_t1", "?")

        lines += [
            f"",
            f"  {sym}  Score: {score}/100  Bias: {bias}  Setup: {setup_type}",
            f"  Entry: {entry_low}–{entry_high}  Stop: {stop}",
            f"  T1: {t1}  (R:R {rr}:1)",
        ]

        cost = pkt.get("costs", {})
        if cost:
            lines.append(
                f"  Cost: {cost.get('round_trip_bps', '?')} bps | "
                f"Net R:R T1: {cost.get('net_rr_t1', '?')}"
            )

    lines += ["", "-" * 50, "Generated by Swing Engine"]
    return "\n".join(lines)


def _build_webhook_payload(packets: dict, regime: dict, alerted: list[str]) -> dict:
    """Build a Slack-compatible blocks payload for the webhook."""
    regime_str = (
        f"*{regime.get('regime', '?').upper()}* | "
        f"Risk: {regime.get('risk_appetite', '?')} | "
        f"VIX: {regime.get('vix_context', '?')}"
    )

    flags = regime.get("caution_flags", [])
    caution_str = f" | :warning: {' | '.join(flags)}" if flags else ""

    header_block = {
        "type": "section",
        "text": {
            "type": "mrkdwn",
            "text": (
                f":chart_with_upwards_trend: *Swing Engine — {date.today().isoformat()}*\n"
                f"{regime_str}{caution_str}"
            ),
        },
    }

    blocks = [header_block, {"type": "divider"}]

    for sym in alerted:
        pkt = packets.get(sym, {})
        sc = pkt.get("score", {})
        ez = pkt.get("entry_zone", {})
        setup = pkt.get("setup", {})
        cost = pkt.get("costs", {})

        score = sc.get("score", 0)
        bias = sc.get("action_bias", "?")
        setup_type = setup.get("type", "?")
        entry_low = ez.get("entry_low", "?")
        entry_high = ez.get("entry_high", "?")
        stop = ez.get("stop", "?")
        t1 = ez.get("target_1", "?")
        rr = ez.get("rr_t1", "?")
        net_rr = cost.get("net_rr_t1")
        net_rr_str = f" (net {net_rr}:1 after costs)" if net_rr else ""

        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"*{sym}*  `{score}/100`  _{bias}_  {setup_type}\n"
                    f"Entry: `{entry_low}–{entry_high}`  Stop: `{stop}`\n"
                    f"T1: `{t1}`  R:R `{rr}:1`{net_rr_str}"
                ),
            },
        })

    return {"blocks": blocks, "text": f"Swing Engine {date.today().isoformat()} — {len(alerted)} alerts"}


# ---------------------------------------------------------------------------
# Public send functions
# ---------------------------------------------------------------------------

def send_email_alert(subject: str, body: str) -> bool:
    """
    Send a plain-text email via SMTP (TLS).

    Credentials sourced from:
        ALERT_EMAIL_FROM, ALERT_EMAIL_PASSWORD, ALERT_EMAIL_TO,
        ALERT_EMAIL_SMTP (default: smtp.gmail.com:465)

    Returns True on success, False on failure. No-ops if not configured.
    """
    if not _is_email_configured():
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = cfg.ALERT_EMAIL_FROM
    msg["To"] = cfg.ALERT_EMAIL_TO
    msg.attach(MIMEText(body, "plain"))

    try:
        context = ssl.create_default_context()
        with smtplib.SMTP_SSL(cfg.ALERT_EMAIL_SMTP, 465, context=context) as server:
            server.login(cfg.ALERT_EMAIL_FROM, cfg.ALERT_EMAIL_PASSWORD)
            server.sendmail(cfg.ALERT_EMAIL_FROM, cfg.ALERT_EMAIL_TO, msg.as_string())
        return True
    except Exception as e:
        print(f"  ALERT: Email send failed: {e}")
        return False


def send_webhook_alert(payload: dict) -> bool:
    """
    POST a JSON payload to the configured webhook URL.

    Slack, Discord, Teams, and generic HTTP webhooks all work.
    Returns True on success, False on failure. No-ops if not configured.
    """
    if not _is_webhook_configured():
        return False

    try:
        data = json.dumps(payload).encode("utf-8")
        req = urllib_request.Request(
            cfg.ALERT_WEBHOOK_URL,
            data=data,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib_request.urlopen(req, timeout=10) as resp:
            return resp.status < 400
    except (URLError, Exception) as e:
        print(f"  ALERT: Webhook send failed: {e}")
        return False


# ---------------------------------------------------------------------------
# Main dispatch
# ---------------------------------------------------------------------------

def dispatch_alerts(packets: dict, regime: dict) -> list[str]:
    """
    Filter packets for high-quality setups and dispatch alerts to all
    configured channels (email + webhook).

    Filtering criteria (from config):
        - action_bias in ALERT_ACTION_BIASES
        - score >= ALERT_MIN_SCORE

    Args:
        packets: Dict of {symbol: packet} from the daily run.
        regime: Regime dict from regime_mod.calc_regime().

    Returns:
        List of symbol strings that triggered alerts.
    """
    min_score = cfg.ALERT_MIN_SCORE
    valid_biases = set(cfg.ALERT_ACTION_BIASES)

    alerted = []
    for sym, pkt in packets.items():
        sc = pkt.get("score", {})
        tradeability = (sc.get("tradeability") or {}).get("score", sc.get("score", 0))
        if sc.get("action_bias") not in valid_biases:
            continue
        if (tradeability or 0) < min_score:
            continue
        alerted.append(sym)

    if not alerted:
        print("  ALERTS: No qualifying setups to alert")
        return []

    # Sort by score descending for readability
    alerted.sort(
        key=lambda s: (packets[s].get("score", {}).get("tradeability") or {}).get(
            "score",
            packets[s].get("score", {}).get("score", 0),
        ),
        reverse=True,
    )

    subject = (
        f"Swing Engine: {len(alerted)} setup(s) — {date.today().isoformat()} | "
        f"{regime.get('regime', '?').upper()}"
    )
    email_body = _build_email_body(packets, regime, alerted)
    webhook_payload = _build_webhook_payload(packets, regime, alerted)

    email_sent = send_email_alert(subject, email_body)
    webhook_sent = send_webhook_alert(webhook_payload)

    if email_sent or webhook_sent:
        channels = []
        if email_sent:
            channels.append("email")
        if webhook_sent:
            channels.append("webhook")
        print(f"  ALERTS: Dispatched {len(alerted)} alert(s) via {', '.join(channels)}: "
              f"{', '.join(alerted)}")
    else:
        print(f"  ALERTS: {len(alerted)} qualifying setup(s) — no channels configured")

    return alerted
